---
# tasks file for php
- name: Install php
  apt: name={{ item }} state=present
  with_items: 
    - php-common
    - php7.0-cli
    - php7.0-common
    - php7.0-fpm
    - php7.0-json
    - php7.0-opcache
    - php7.0-readline
    - php7.0-mysql
    - php7.0
    - php7.0-gd

